const $=id=>document.getElementById(id);let type="Estimate",photos=[];
function money(n){return new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(Number(n)||0)}
function nextNo(){let y=new Date().getFullYear(),k="ontboom_seq_"+y,n=(+localStorage.getItem(k)||0)+1;return "ONT-"+y+"-"+String(n).padStart(4,"0")}
function commitNo(){let y=new Date().getFullYear(),k="ontboom_seq_"+y;localStorage.setItem(k,(+localStorage.getItem(k)||0)+1)}
function addItem(v={description:"",qty:1,rate:""}){let d=document.createElement("div");d.className="item";d.innerHTML='<input class="desc" placeholder="Description"><input class="qty" type="number" min="0" step="1"><input class="rate" type="number" min="0" step=".01" placeholder="Rate"><button class="remove">×</button>';d.querySelector(".desc").value=v.description;d.querySelector(".qty").value=v.qty;d.querySelector(".rate").value=v.rate;d.querySelectorAll("input").forEach(x=>x.oninput=render);d.querySelector(".remove").onclick=()=>{d.remove();render()};$("items").appendChild(d);render()}
function data(){return{photos,includePhotos:$("includePhotos").checked,type,no:$("docNo").value,date:$("date").value,customer:$("customer").value,cell:$("customerCell").value,address:$("customerAddress").value,notes:$("notes").value,days:$("days").value,items:[...document.querySelectorAll(".item")].map(r=>({description:r.querySelector(".desc").value,qty:+r.querySelector(".qty").value||0,rate:+r.querySelector(".rate").value||0}))}}
function render(){let d=data();renderPhotos();$("pType").textContent=d.type.toUpperCase();$("pNo").textContent=d.no;$("pDate").textContent=d.date;$("pCustomer").textContent=[d.customer,d.cell,d.address].filter(Boolean).join("\n")||"—";$("pItems").innerHTML="";let total=0;d.items.forEach(i=>{let a=i.qty*i.rate;total+=a;let tr=document.createElement("tr");tr.innerHTML="<td></td><td></td><td></td><td></td>";tr.children[0].textContent=i.description;tr.children[1].textContent=i.qty;tr.children[2].textContent=money(i.rate);tr.children[3].textContent=money(a);$("pItems").appendChild(tr)});$("pTotal").textContent=money(total);$("pNotes").textContent=d.notes||"—";$("pTerms").innerHTML="<b>"+(d.type==="Estimate"?"Validity":"Payment terms")+":</b> "+d.days+" days"}
function reset(){type="Estimate";photos=[];$("includePhotos").checked=false;function renderPhotos(){$("photoPreview").innerHTML="";photos.forEach((src,i)=>{let d=document.createElement("div");d.className="photo-card";let img=document.createElement("img");img.src=src;let b=document.createElement("button");b.type="button";b.textContent="×";b.onclick=()=>{photos.splice(i,1);render()};d.append(img,b);$("photoPreview").appendChild(d)});$("pPhotos").innerHTML="";photos.forEach(src=>{let img=document.createElement("img");img.src=src;$("pPhotos").appendChild(img)});$("pPhotoSection").classList.toggle("show",$("includePhotos").checked&&photos.length>0)}function addPhotoFile(f){if(!f.type.startsWith("image/"))return;let reader=new FileReader();reader.onload=()=>{let img=new Image();img.onload=()=>{let max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);photos.push(canvas.toDataURL("image/jpeg",.72));render()};img.src=reader.result};reader.readAsDataURL(f)}
document.querySelectorAll(".tab").forEach((b,i)=>b.classList.toggle("active",i===0));$("docNo").value=nextNo();$("date").value=new Date().toISOString().slice(0,10);["customer","customerCell","customerAddress","notes"].forEach(x=>$(x).value="");$("days").value=7;$("items").innerHTML="";addItem();render()}
function save(){let d=data();if(!d.customer)return alert("Enter the customer name first.");let all=JSON.parse(localStorage.getItem("ontboom_docs")||"[]");let ix=all.findIndex(x=>x.no===d.no);if(ix<0){all.unshift(d);commitNo();$("docNo").value=nextNo()}else all[ix]=d;localStorage.setItem("ontboom_docs",JSON.stringify(all));showSaved();alert("Saved on this device.");render()}
function load(no){let d=JSON.parse(localStorage.getItem("ontboom_docs")||"[]").find(x=>x.no===no);if(!d)return;type=d.type;photos=d.photos||[];$("includePhotos").checked=!!d.includePhotos;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$("docNo").value=d.no;$("date").value=d.date;$("customer").value=d.customer;$("customerCell").value=d.cell;$("customerAddress").value=d.address;$("notes").value=d.notes;$("days").value=d.days;$("items").innerHTML="";d.items.forEach(addItem);render();scrollTo(0,0)}
function showSaved(){let a=JSON.parse(localStorage.getItem("ontboom_docs")||"[]");$("saved").innerHTML=a.length?"":"No saved documents yet.";a.forEach(d=>{let r=document.createElement("div");r.className="saved-row";let s=document.createElement("span");s.textContent=d.no+" — "+d.customer+" ("+d.type+")";let b=document.createElement("button");b.textContent="Open";b.onclick=()=>load(d.no);r.append(s,b);$("saved").appendChild(r)})}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{type=b.dataset.type;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));render()});
["docNo","date","customer","customerCell","customerAddress","notes","days"].forEach(x=>$(x).oninput=render);$("photoUpload").onchange=e=>{[...(e.target.files||[])].slice(0,20-photos.length).forEach(addPhotoFile);e.target.value=""};$("includePhotos").onchange=render;$("addItem").onclick=()=>addItem();$("newDoc").onclick=reset;$("save").onclick=save;function showLogo(){let src=localStorage.getItem("ontboom_logo")||"",img=$("pLogo"),fallback=$("brandFallback");if(src){img.src=src;img.classList.add("has-logo");fallback.style.display="none"}else{img.removeAttribute("src");img.classList.remove("has-logo");fallback.style.display=""}}$("logoUpload").onchange=e=>{let f=e.target.files&&e.target.files[0];if(!f)return;if(f.size>3000000)return alert("Please choose a logo smaller than 3 MB.");let reader=new FileReader();reader.onload=()=>{localStorage.setItem("ontboom_logo",reader.result);showLogo()};reader.readAsDataURL(f)};$("removeLogo").onclick=()=>{localStorage.removeItem("ontboom_logo");$("logoUpload").value="";showLogo()};$("print").onclick=()=>window.print();showLogo();reset();showSaved();