const ontboomCloud=(()=>{const fb=window.ontboomFirebase;if(!fb)return null;const auth=fb.auth,db=fb.db;let uid=null;const msg=t=>{const e=document.getElementById('loginMessage');if(e)e.textContent=t||''};async function uploadLocal(){if(!uid)return;const documents=JSON.parse(localStorage.getItem('ontboom_docs')||'[]');const customers=JSON.parse(localStorage.getItem('ontboom_customers')||'[]');await db.collection('users').doc(uid).collection('data').doc('backup').set({documents,customers,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}async function downloadCloud(){if(!uid)return;const s=await db.collection('users').doc(uid).collection('data').doc('backup').get();if(!s.exists){await uploadLocal();return}const d=s.data()||{};if(Array.isArray(d.documents))localStorage.setItem('ontboom_docs',JSON.stringify(d.documents));if(Array.isArray(d.customers))localStorage.setItem('ontboom_customers',JSON.stringify(d.customers));if(typeof showSaved==='function')showSaved();if(typeof updateDashboard==='function')updateDashboard();if(typeof refreshCustomers==='function')refreshCustomers()}async function login(){const email=document.getElementById('loginEmail').value.trim(),password=document.getElementById('loginPassword').value;if(!email||!password)return msg('Enter your email and password.');msg('Signing in...');try{await auth.signInWithEmailAndPassword(email,password);document.getElementById('loginPassword').value=''}catch(e){msg('Could not sign in. Check your email and password.')}}function logout(){return auth.signOut()}auth.onAuthStateChanged(async user=>{uid=user?user.uid:null;document.getElementById('loginPanel').hidden=!!user;document.getElementById('appShell').hidden=!user;if(user){msg('');try{await downloadCloud()}catch(e){console.error('Cloud load failed',e)}}});document.getElementById('loginButton').addEventListener('click',login);document.getElementById('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});document.getElementById('logoutButton').addEventListener('click',logout);window.addEventListener('ontboom-data-changed',()=>uploadLocal().catch(console.error));return{uploadLocal,downloadCloud}})();

/* Ontboom mobile send workflow.
   The PDF is prepared before the user taps Send. This preserves Android's
   required user gesture so the native share sheet can open immediately. */
setTimeout(()=>{const btn=document.getElementById('send'),hint=document.getElementById('shareHint');if(!btn||typeof data!=='function')return;let prepared=null,timer=null,busy=false,version=0;
function filenameFor(d){return 'Ontboom-'+d.type+'-'+(d.no||'Document')+'.pdf'}
function shareText(d){return 'Good day '+(d.customer||'')+',\n\nPlease find attached your Ontboom '+d.type.toLowerCase()+' '+d.no+'.\n\nKind regards,\nFrik\nONTBOOM\n065 225 8354'}
async function buildPdf(){if(busy||typeof html2pdf==='undefined')return;busy=true;const myVersion=version;try{render();const d=data(),filename=filenameFor(d),opt={margin:[10,10,10,10],filename,image:{type:'jpeg',quality:.96},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff',letterRendering:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy'],avoid:['tr','.client-box','.summary-row','.terms','.doc-notes']}};const blob=await html2pdf().set(opt).from(document.getElementById('document')).outputPdf('blob');if(myVersion!==version)return;const file=new File([blob],filename,{type:'application/pdf',lastModified:Date.now()});prepared={d,blob,file,filename};if(hint){hint.style.display='none';hint.textContent=''}btn.disabled=false;btn.textContent='Send '+d.type}catch(e){console.error('PDF preparation failed',e);prepared=null;btn.disabled=false;btn.textContent='Send '+type}finally{busy=false}}
function schedule(){version++;prepared=null;clearTimeout(timer);btn.disabled=true;btn.textContent='Preparing '+type+'...';timer=setTimeout(buildPdf,700)}
function markSent(d){if(d.type==='Estimate'){document.getElementById('estimateStatus').value='Sent';const x=data();x.status='Sent';persist(x,false);render()}}
btn.onclick=function(){const d=data();if(!d.customer)return alert('Enter the customer name first.');if(!prepared){schedule();return alert('Your '+d.type.toLowerCase()+' is still being prepared. Please tap Send again in a moment.')}const r=prepared;if(!navigator.share){downloadPdf(r.blob,r.filename);return alert('This browser cannot open the Android share menu. The PDF was saved to Downloads.')}const payload={title:'Ontboom '+r.d.type+' '+r.d.no,text:shareText(r.d),files:[r.file]};if(navigator.canShare&&!navigator.canShare({files:[r.file]})){downloadPdf(r.blob,r.filename);return alert('This browser cannot share PDF files directly. The PDF was saved to Downloads.')}try{const p=navigator.share(payload);p.then(()=>markSent(r.d)).catch(e=>{if(e&&e.name!=='AbortError'){console.error('Native share failed',e);downloadPdf(r.blob,r.filename);alert('Android could not open the share menu. The PDF was saved to Downloads.')}})}catch(e){console.error('Native share failed',e);downloadPdf(r.blob,r.filename);alert('Android could not open the share menu. The PDF was saved to Downloads.')}};
const oldRender=render;render=function(){oldRender();clearTimeout(timer);version++;prepared=null;timer=setTimeout(buildPdf,700)};
document.addEventListener('input',e=>{if(e.target&&e.target.closest&&e.target.closest('.card'))schedule()});document.addEventListener('change',e=>{if(e.target&&e.target.closest&&e.target.closest('.card'))schedule()});schedule();
},0);