(function(){
const KEY='ontboom_job_status';
const statuses=['Scheduled','In Progress','Completed'];
function docs(){try{return JSON.parse(localStorage.getItem('ontboom_docs')||'[]')}catch(e){return[]}}
function states(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function saveStates(x){localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new Event('ontboom-data-changed'))}
function accepted(){return docs().filter(d=>d.type==='Estimate'&&(d.status||'Draft')==='Accepted')}
function ensureUI(){if(document.getElementById('jobManager'))return;const saved=document.getElementById('saved');if(!saved)return;const section=saved.closest('section');if(!section)return;const box=document.createElement('section');box.id='jobManager';box.className='card no-print';box.innerHTML='<div class="job-head"><div><h3>Active Jobs</h3><p class="job-sub">Accepted estimates become jobs automatically.</p></div><span id="jobCount" class="job-count">0</span></div><div class="job-summary"><div><strong id="jobScheduled">0</strong><span>Scheduled</span></div><div><strong id="jobProgress">0</strong><span>In Progress</span></div><div><strong id="jobCompleted">0</strong><span>Completed</span></div></div><div id="jobList"></div>';
section.parentNode.insertBefore(box,section);
}
function setStatus(no,status){const x=states();x[no]=status;saveStates(x);renderJobs()}
function renderJobs(){ensureUI();const list=document.getElementById('jobList');if(!list)return;const jobs=accepted(),x=states();let scheduled=0,progress=0,completed=0;list.innerHTML='';jobs.forEach(d=>{let st=x[d.no]||'Scheduled';if(st==='Scheduled')scheduled++;else if(st==='In Progress')progress++;else if(st==='Completed')completed++;const row=document.createElement('div');row.className='job-row';const info=document.createElement('div');info.className='job-info';const title=document.createElement('strong');title.textContent=d.customer||'Customer';const meta=document.createElement('span');meta.textContent=d.no+' • '+(d.cell||'No cellphone');info.append(title,meta);const select=document.createElement('select');select.className='job-status';statuses.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;o.selected=s===st;select.appendChild(o)});select.onchange=()=>setStatus(d.no,select.value);const open=document.createElement('button');open.type='button';open.className='secondary job-open';open.textContent='Open Estimate';open.onclick=()=>{if(typeof load==='function')load(d.no)};row.append(info,select,open);list.appendChild(row)});if(!jobs.length)list.innerHTML='<p class="job-empty">No active jobs yet. When an estimate is marked Accepted and saved, it will appear here.</p>';document.getElementById('jobCount').textContent=jobs.filter(d=>(x[d.no]||'Scheduled')!=='Completed').length;document.getElementById('jobScheduled').textContent=scheduled;document.getElementById('jobProgress').textContent=progress;document.getElementById('jobCompleted').textContent=completed}
window.addEventListener('ontboom-data-changed',()=>setTimeout(renderJobs,0));window.addEventListener('storage',renderJobs);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderJobs);else renderJobs();
})();
