// Ontboom Android send flow.
function ontboomClientMessage(d){return `Good day ${d.customer},\n\nPlease find attached your Ontboom ${d.type.toLowerCase()} ${d.no}.\n\nKind regards,\nFrik\nONTBOOM\n065 225 8354`;}
function ontboomPhone(cell){let n=String(cell||"").replace(/\D/g,"");if(n.startsWith("0"))n="27"+n.slice(1);return n;}
function ontboomOpenWhatsApp(d){const phone=ontboomPhone(d.cell),text=encodeURIComponent(ontboomClientMessage(d));window.location.href=phone?`https://wa.me/${phone}?text=${text}`:`https://wa.me/?text=${text}`;}
function ontboomMarkSent(d){if(d.type==="Estimate"&&d.status==="Draft"){$("estimateStatus").value="Sent";const x=data();x.status="Sent";persist(x,false);render();}saveCustomer(d);cloudChanged();}
async function ontboomSendDocument(){const d=data();if(!d.customer){alert("Enter the customer name first.");return;}if(!preparedShare||preparedShare.key!==currentShareKey()){scheduleShare();alert("Preparing your PDF. Tap Send again in a moment.");return;}const r=preparedShare;if(navigator.share){try{const payload={files:[r.file]};if(!navigator.canShare||navigator.canShare(payload)){await navigator.share(payload);ontboomMarkSent(r.d);return;}}catch(e){if(e&&e.name==="AbortError")return;console.warn("Native PDF share unavailable; using WhatsApp fallback",e);}}downloadPdf(r.blob,r.filename);ontboomMarkSent(r.d);const go=confirm(`The PDF has been saved as ${r.filename}.\n\nTap OK to open WhatsApp for ${r.d.customer}. Then tap the paperclip → Document and select this PDF from Downloads.`);if(go)ontboomOpenWhatsApp(r.d);}
const ontboomSendButton=document.getElementById("send");if(ontboomSendButton)ontboomSendButton.onclick=ontboomSendDocument;

(function(){
 const KEY="ontboom_document_settings_v1";
 const defaults={businessName:"ONTBOOM",serviceLine:"Tree-Felling & Pruning Services",businessAddress:"Zwavelpoort, Pretoria",businessPhone:"065 225 8354",businessEmail:"frik.ontboom@gmail.com",vatText:"Not VAT registered",colDescription:"DESCRIPTION",colQty:"QTY",colRate:"RATE",colAmount:"AMOUNT",extraTerms:"All work is subject to the agreed scope above. Any additional work requested may be quoted separately.",footerService:"Tree-Felling & Pruning Services",footerTagline:"A cleaner, greener tomorrow."};
 function settings(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"));}catch(e){return {...defaults};}}
 function applySettings(){const s=settings(),bd=document.querySelector(".business-details");if(bd){bd.innerHTML="";const b=document.createElement("b");b.textContent=s.businessName;bd.append(b,document.createElement("br"));const vals=[s.serviceLine,s.businessAddress,s.businessPhone,s.businessEmail].filter(Boolean);vals.forEach((v,i)=>{bd.append(document.createTextNode(v));if(i<vals.length-1)bd.append(document.createElement("br"));});}const f=document.getElementById("brandFallback");if(f){const h=f.querySelector("h2"),st=f.querySelector("strong");if(h)h.textContent=s.businessName;if(st)st.textContent=s.serviceLine;}const vat=document.querySelector(".vat-note");if(vat)vat.textContent=s.vatText;const heads=document.querySelectorAll(".doc-table thead th");[s.colDescription,s.colQty,s.colRate,s.colAmount].forEach((v,i)=>{if(heads[i])heads[i].textContent=v;});const terms=document.querySelector(".terms");if(terms){const ps=terms.querySelectorAll("p");if(ps[1])ps[1].textContent=s.extraTerms;}const footer=document.querySelector(".paper footer");if(footer){footer.innerHTML="";const b=document.createElement("b");b.textContent=s.businessName;footer.append(b,document.createTextNode(" • "+s.footerService+" • "+s.businessPhone),document.createElement("br"));const span=document.createElement("span");span.textContent=s.footerTagline;footer.append(span);}}
 function saveSettings(){const s={};Object.keys(defaults).forEach(k=>{const el=document.getElementById("set_"+k);s[k]=el?el.value:defaults[k];});localStorage.setItem(KEY,JSON.stringify(s));applySettings();if(typeof scheduleShare==="function")scheduleShare();}
 function buildSetup(){const card=document.querySelector("main > section.card.no-print");if(!card||document.getElementById("documentSettings"))return;const box=document.createElement("div");box.id="documentSettings";box.className="setup-panel";box.hidden=true;box.innerHTML='<h2>Set Up</h2><p class="setup-help">Business and document settings. Changes are saved automatically on this device.</p><div class="grid"><label>Business name<input id="set_businessName"></label><label>Service description<input id="set_serviceLine"></label><label>Business address<input id="set_businessAddress"></label><label>Phone<input id="set_businessPhone"></label><label class="wide">Email<input id="set_businessEmail" type="email"></label><label class="wide">VAT wording<input id="set_vatText"></label><label>Description heading<input id="set_colDescription"></label><label>Quantity heading<input id="set_colQty"></label><label>Rate heading<input id="set_colRate"></label><label>Amount heading<input id="set_colAmount"></label><label class="wide">Terms wording<textarea id="set_extraTerms" rows="3"></textarea></label><label>Footer service text<input id="set_footerService"></label><label>Footer tagline<input id="set_footerTagline"></label></div>';
  card.appendChild(box);const s=settings();Object.keys(defaults).forEach(k=>{const el=document.getElementById("set_"+k);if(el){el.value=s[k];el.addEventListener("input",saveSettings);}});
  const tabs=card.querySelector(".tabs"),setup=document.createElement("button");setup.type="button";setup.className="tab";setup.id="setupTab";setup.textContent="Set Up";tabs.appendChild(setup);
  const logo=card.querySelector(".logo-settings"),formEls=[...card.children].filter(el=>el!==tabs&&el!==box&&el!==logo);
  function showSetup(on){box.hidden=!on;if(logo)logo.hidden=!on;formEls.forEach(el=>el.hidden=on);tabs.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",on?t===setup:(t.dataset.type===window.currentType)));if(!on&&typeof render==="function")render();}
  setup.addEventListener("click",()=>showSetup(true));tabs.querySelectorAll('.tab[data-type]').forEach(t=>t.addEventListener("click",()=>showSetup(false)));
 }
 buildSetup();applySettings();
 const originalRender=window.render;if(typeof originalRender==="function")window.render=function(){originalRender.apply(this,arguments);applySettings();};
})();
